spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect