spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: liquibase/v1/changelog.sql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgress
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect